apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 2
    requireLogin: true
    persistenceEnabled: true
    journalType: nio
    messageMigration: true
    storage:
      size: 1Gi
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "2Gi"
  console:
    expose: true
  acceptors:
    - name: core
      port: 61616
      protocols: core
    - name: amqp
      port: 5672
      protocols: amqp
  addressSettings:
    applyRule: merge_all
    addressSetting:
      - match: "#"
        redistributionDelay: 5000
  brokerProperties:
    - "globalMaxSize=1GiB"
    - "clusterConfigurations.my-cluster.messageLoadBalancingType=OFF_WITH_REDISTRIBUTION"
    - "AMQPConnections.dc1-to-dc2.uri=tcp://${DC2_HOST}:${DC2_PORT}"
    - "AMQPConnections.dc1-to-dc2.user=${DC2_USER}"
    - "AMQPConnections.dc1-to-dc2.password=${DC2_PASS}"
    - "AMQPConnections.dc1-to-dc2.connectionElements.mirror.type=MIRROR"
    - "AMQPConnections.dc1-to-dc2.connectionElements.mirror.addressFilter=app.foo"
    - "AMQPConnections.dc1-to-dc2.connectionElements.mirror.messageAcknowledgments=true"
    - "AMQPConnections.dc1-to-dc2.connectionElements.mirror.queueRemoval=true"
    - "AMQPConnections.dc1-to-dc2.connectionElements.mirror.queueCreation=true"
