---
# vars file for artemis-operator
artemis_operator_yamls:
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/crds/broker_activemqartemis_crd.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/crds/broker_activemqartemisaddress_crd.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/crds/broker_activemqartemisscaledown_crd.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/crds/broker_activemqartemissecurity_crd.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/service_account.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/role.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/role_binding.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/election_role.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/election_role_binding.yaml
  - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/main/deploy/operator.yaml
